#!/bin/bash

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
echo "Current branch: $CURRENT_BRANCH"
echo "Commits between dev and $CURRENT_BRANCH:"
git log origin/dev..origin/$CURRENT_BRANCH --pretty=format:'- %h %s'
